export const cities = [
  { city: "Mexico City", airport: "MEX", region: "Latin America" },
  { city: "Sao Paulo", airport: "GRU", region: "Latin America" },
  { city: "Buenos Aires", airport: "EZE", region: "Latin America" },
  { city: "Rio de Janeiro", airport: "GIG", region: "Latin America" },
  { city: "Lima", airport: "LIM", region: "Latin America" },
  { city: "Bogota", airport: "BOG", region: "Latin America" },
  { city: "Santiago", airport: "SCL", region: "Latin America" },
  { city: "Medellin", airport: "MDE", region: "Latin America" },
  { city: "Cali", airport: "CLO", region: "Latin America" },
  { city: "Cartagena", airport: "CTG", region: "Latin America" },

  { city: "New York", airport: "JFK", region: "United States" },
  { city: "Los Angeles", airport: "LAX", region: "United States" },
  { city: "Chicago", airport: "ORD", region: "United States" },
  { city: "Houston", airport: "IAH", region: "United States" },
  { city: "Phoenix", airport: "PHX", region: "United States" },
  { city: "Dallas", airport: "DFW", region: "United States" },
  { city: "Miami", airport: "MIA", region: "United States" },
  { city: "Atlanta", airport: "ATL", region: "United States" },
  { city: "Seattle", airport: "SEA", region: "United States" },
  { city: "San Francisco", airport: "SFO", region: "United States" },

  { city: "London", airport: "LHR", region: "Europe" },
  { city: "Paris", airport: "CDG", region: "Europe" },
  { city: "Madrid", airport: "MAD", region: "Europe" },
  { city: "Rome", airport: "FCO", region: "Europe" },
  { city: "Amsterdam", airport: "AMS", region: "Europe" },
  { city: "Frankfurt", airport: "FRA", region: "Europe" },
  { city: "Barcelona", airport: "BCN", region: "Europe" },
  { city: "Lisbon", airport: "LIS", region: "Europe" },
  { city: "Istanbul", airport: "IST", region: "Europe" },
  { city: "Athens", airport: "ATH", region: "Europe" },

  { city: "Tokyo", airport: "HND", region: "Asia" },
  { city: "Delhi", airport: "DEL", region: "Asia" },
  { city: "Shanghai", airport: "PVG", region: "Asia" },
  { city: "Beijing", airport: "PEK", region: "Asia" },
  { city: "Mumbai", airport: "BOM", region: "Asia" },
  { city: "Seoul", airport: "ICN", region: "Asia" },
  { city: "Bangkok", airport: "BKK", region: "Asia" },
  { city: "Singapore", airport: "SIN", region: "Asia" },
  { city: "Hong Kong", airport: "HKG", region: "Asia" },
  { city: "Dubai", airport: "DXB", region: "Asia" }
];

export const rewardsPrograms = [
  { name: "American AAdvantage", type: "airline", alliance: "oneworld", transferPartners: ["Bilt", "Marriott"] },
  { name: "Alaska Mileage Plan", type: "airline", alliance: "oneworld", transferPartners: ["Bilt", "Marriott"] },
  { name: "United MileagePlus", type: "airline", alliance: "Star Alliance", transferPartners: ["Chase", "Bilt", "Marriott"] },
  { name: "Delta SkyMiles", type: "airline", alliance: "SkyTeam", transferPartners: ["Amex", "Marriott"] },
  { name: "Air Canada Aeroplan", type: "airline", alliance: "Star Alliance", transferPartners: ["Amex", "Chase", "Capital One", "Bilt", "Marriott"] },
  { name: "Flying Blue", type: "airline", alliance: "SkyTeam", transferPartners: ["Amex", "Chase", "Citi", "Capital One", "Bilt", "Marriott"] },
  { name: "British Airways Executive Club", type: "airline", alliance: "oneworld", transferPartners: ["Amex", "Chase", "Capital One", "Bilt", "Marriott"] },
  { name: "Iberia Plus", type: "airline", alliance: "oneworld", transferPartners: ["Amex", "Chase", "Bilt", "Marriott"] },
  { name: "Qatar Airways Privilege Club", type: "airline", alliance: "oneworld", transferPartners: ["Amex", "Citi", "Capital One", "Bilt", "Marriott"] },
  { name: "Virgin Atlantic Flying Club", type: "airline", alliance: "SkyTeam", transferPartners: ["Amex", "Chase", "Citi", "Capital One", "Bilt", "Marriott"] },
  { name: "Singapore KrisFlyer", type: "airline", alliance: "Star Alliance", transferPartners: ["Amex", "Chase", "Citi", "Capital One", "Marriott"] },
  { name: "Emirates Skywards", type: "airline", alliance: "Independent", transferPartners: ["Amex", "Chase", "Citi", "Capital One", "Bilt", "Marriott"] },
  { name: "Etihad Guest", type: "airline", alliance: "Independent", transferPartners: ["Amex", "Citi", "Capital One", "Marriott"] },
  { name: "Turkish Miles&Smiles", type: "airline", alliance: "Star Alliance", transferPartners: ["Citi", "Capital One", "Bilt", "Marriott"] },
  { name: "Avianca LifeMiles", type: "airline", alliance: "Star Alliance", transferPartners: ["Amex", "Citi", "Capital One", "Bilt", "Marriott"] },
  { name: "Cathay Pacific Asia Miles", type: "airline", alliance: "oneworld", transferPartners: ["Amex", "Citi", "Capital One", "Bilt", "Marriott"] },
  { name: "ANA Mileage Club", type: "airline", alliance: "Star Alliance", transferPartners: ["Amex", "Marriott"] },
  { name: "Qantas Frequent Flyer", type: "airline", alliance: "oneworld", transferPartners: ["Amex", "Capital One", "Citi", "Marriott"] },
  { name: "TAP Miles&Go", type: "airline", alliance: "Star Alliance", transferPartners: ["Capital One", "Marriott"] },
  { name: "Southwest Rapid Rewards", type: "airline", alliance: "Independent", transferPartners: ["Chase", "Marriott"] },
  { name: "JetBlue TrueBlue", type: "airline", alliance: "Independent", transferPartners: ["Chase", "Citi", "Capital One", "Marriott"] },
  { name: "Hilton Honors", type: "hotel", alliance: "Hotel", transferPartners: ["Amex", "Bilt"] },
  { name: "Marriott Bonvoy", type: "hotel", alliance: "Hotel", transferPartners: ["Amex", "Chase", "Citi", "Capital One", "Bilt"] },
  { name: "World of Hyatt", type: "hotel", alliance: "Hotel", transferPartners: ["Chase", "Bilt"] },
  { name: "IHG One Rewards", type: "hotel", alliance: "Hotel", transferPartners: ["Chase", "Bilt"] }
];

export const airlineInfo = {
  "American AAdvantage": { name: "American Airlines", emoji: "🇺🇸", cashUrl: "https://www.aa.com/", pointsUrl: "https://www.aa.com/" },
  "Alaska Mileage Plan": { name: "Alaska Airlines", emoji: "🇺🇸", cashUrl: "https://www.alaskaair.com/", pointsUrl: "https://www.alaskaair.com/" },
  "United MileagePlus": { name: "United Airlines", emoji: "🇺🇸", cashUrl: "https://www.united.com/", pointsUrl: "https://www.united.com/" },
  "Delta SkyMiles": { name: "Delta Air Lines", emoji: "🇺🇸", cashUrl: "https://www.delta.com/", pointsUrl: "https://www.delta.com/" },
  "Air Canada Aeroplan": { name: "Air Canada", emoji: "🇨🇦", cashUrl: "https://www.aircanada.com/", pointsUrl: "https://www.aircanada.com/" },
  "Flying Blue": { name: "Air France / KLM", emoji: "🇫🇷", cashUrl: "https://www.flyingblue.com/", pointsUrl: "https://www.flyingblue.com/" },
  "British Airways Executive Club": { name: "British Airways", emoji: "🇬🇧", cashUrl: "https://www.britishairways.com/", pointsUrl: "https://www.britishairways.com/" },
  "Iberia Plus": { name: "Iberia", emoji: "🇪🇸", cashUrl: "https://www.iberia.com/", pointsUrl: "https://www.iberia.com/" },
  "Qatar Airways Privilege Club": { name: "Qatar Airways", emoji: "🇶🇦", cashUrl: "https://www.qatarairways.com/", pointsUrl: "https://www.qatarairways.com/" },
  "Virgin Atlantic Flying Club": { name: "Virgin Atlantic", emoji: "🇬🇧", cashUrl: "https://www.virginatlantic.com/", pointsUrl: "https://www.virginatlantic.com/" },
  "Singapore KrisFlyer": { name: "Singapore Airlines", emoji: "🇸🇬", cashUrl: "https://www.singaporeair.com/", pointsUrl: "https://www.singaporeair.com/" },
  "Emirates Skywards": { name: "Emirates", emoji: "🇦🇪", cashUrl: "https://www.emirates.com/", pointsUrl: "https://www.emirates.com/" },
  "Etihad Guest": { name: "Etihad Airways", emoji: "🇦🇪", cashUrl: "https://www.etihad.com/", pointsUrl: "https://www.etihad.com/" },
  "Turkish Miles&Smiles": { name: "Turkish Airlines", emoji: "🇹🇷", cashUrl: "https://www.turkishairlines.com/", pointsUrl: "https://www.turkishairlines.com/" },
  "Avianca LifeMiles": { name: "Avianca", emoji: "🇨🇴", cashUrl: "https://www.avianca.com/", pointsUrl: "https://www.lifemiles.com/" },
  "Cathay Pacific Asia Miles": { name: "Cathay Pacific", emoji: "🇭🇰", cashUrl: "https://www.cathaypacific.com/", pointsUrl: "https://www.cathaypacific.com/" },
  "ANA Mileage Club": { name: "ANA", emoji: "🇯🇵", cashUrl: "https://www.ana.co.jp/", pointsUrl: "https://www.ana.co.jp/" },
  "Qantas Frequent Flyer": { name: "Qantas", emoji: "🇦🇺", cashUrl: "https://www.qantas.com/", pointsUrl: "https://www.qantas.com/" },
  "TAP Miles&Go": { name: "TAP Air Portugal", emoji: "🇵🇹", cashUrl: "https://www.flytap.com/", pointsUrl: "https://www.flytap.com/" },
  "Southwest Rapid Rewards": { name: "Southwest", emoji: "🇺🇸", cashUrl: "https://www.southwest.com/", pointsUrl: "https://www.southwest.com/" },
  "JetBlue TrueBlue": { name: "JetBlue", emoji: "🇺🇸", cashUrl: "https://www.jetblue.com/", pointsUrl: "https://www.jetblue.com/" },
  "Hilton Honors": { name: "Hilton", emoji: "🏨", cashUrl: "https://www.hilton.com/", pointsUrl: "https://www.hilton.com/" },
  "Marriott Bonvoy": { name: "Marriott", emoji: "🏨", cashUrl: "https://www.marriott.com/", pointsUrl: "https://www.marriott.com/" },
  "World of Hyatt": { name: "Hyatt", emoji: "🏨", cashUrl: "https://world.hyatt.com/", pointsUrl: "https://world.hyatt.com/" },
  "IHG One Rewards": { name: "IHG", emoji: "🏨", cashUrl: "https://www.ihg.com/", pointsUrl: "https://www.ihg.com/" }
};
