export const cities = [
  // Latin America (100)
  { city: "Mexico City", airport: "MEX", region: "Latin America" },
  { city: "Sao Paulo", airport: "GRU", region: "Latin America" },
  { city: "Buenos Aires", airport: "EZE", region: "Latin America" },
  { city: "Rio de Janeiro", airport: "GIG", region: "Latin America" },
  { city: "Lima", airport: "LIM", region: "Latin America" },
  { city: "Bogota", airport: "BOG", region: "Latin America" },
  { city: "Santiago", airport: "SCL", region: "Latin America" },
  { city: "Belo Horizonte", airport: "CNF", region: "Latin America" },
  { city: "Guadalajara", airport: "GDL", region: "Latin America" },
  { city: "Monterrey", airport: "MTY", region: "Latin America" },
  { city: "Brasilia", airport: "BSB", region: "Latin America" },
  { city: "Salvador", airport: "SSA", region: "Latin America" },
  { city: "Fortaleza", airport: "FOR", region: "Latin America" },
  { city: "Recife", airport: "REC", region: "Latin America" },
  { city: "Porto Alegre", airport: "POA", region: "Latin America" },
  { city: "Curitiba", airport: "CWB", region: "Latin America" },
  { city: "Manaus", airport: "MAO", region: "Latin America" },
  { city: "Belem", airport: "BEL", region: "Latin America" },
  { city: "Goiania", airport: "GYN", region: "Latin America" },
  { city: "Campinas", airport: "VCP", region: "Latin America" },
  { city: "Asuncion", airport: "ASU", region: "Latin America" },
  { city: "Quito", airport: "UIO", region: "Latin America" },
  { city: "Guayaquil", airport: "GYE", region: "Latin America" },
  { city: "La Paz", airport: "LPB", region: "Latin America" },
  { city: "Santa Cruz", airport: "VVI", region: "Latin America" },
  { city: "Medellin", airport: "MDE", region: "Latin America" },
  { city: "Cali", airport: "CLO", region: "Latin America" },
  { city: "Cartagena", airport: "CTG", region: "Latin America" },
  { city: "Barranquilla", airport: "BAQ", region: "Latin America" },
  { city: "Bucaramanga", airport: "BGA", region: "Latin America" },
  { city: "Pereira", airport: "PEI", region: "Latin America" },
  { city: "Cucuta", airport: "CUC", region: "Latin America" },
  { city: "Santa Marta", airport: "SMR", region: "Latin America" },
  { city: "Panama City", airport: "PTY", region: "Latin America" },
  { city: "San Jose", airport: "SJO", region: "Latin America" },
  { city: "San Salvador", airport: "SAL", region: "Latin America" },
  { city: "Guatemala City", airport: "GUA", region: "Latin America" },
  { city: "Tegucigalpa", airport: "XPL", region: "Latin America" },
  { city: "Managua", airport: "MGA", region: "Latin America" },
  { city: "Santo Domingo", airport: "SDQ", region: "Latin America" },
  { city: "Punta Cana", airport: "PUJ", region: "Latin America" },
  { city: "San Juan", airport: "SJU", region: "Latin America" },
  { city: "Havana", airport: "HAV", region: "Latin America" },
  { city: "Montevideo", airport: "MVD", region: "Latin America" },
  { city: "Cordoba", airport: "COR", region: "Latin America" },
  { city: "Rosario", airport: "ROS", region: "Latin America" },
  { city: "Mendoza", airport: "MDZ", region: "Latin America" },
  { city: "Mar del Plata", airport: "MDQ", region: "Latin America" },
  { city: "San Miguel de Tucuman", airport: "TUC", region: "Latin America" },
  { city: "La Plata", airport: "EZE", region: "Latin America" },
  { city: "Tijuana", airport: "TIJ", region: "Latin America" },
  { city: "Puebla", airport: "PBC", region: "Latin America" },
  { city: "Leon", airport: "BJX", region: "Latin America" },
  { city: "Merida", airport: "MID", region: "Latin America" },
  { city: "Cancun", airport: "CUN", region: "Latin America" },
  { city: "Queretaro", airport: "QRO", region: "Latin America" },
  { city: "San Luis Potosi", airport: "SLP", region: "Latin America" },
  { city: "Aguascalientes", airport: "AGU", region: "Latin America" },
  { city: "Veracruz", airport: "VER", region: "Latin America" },
  { city: "Oaxaca", airport: "OAX", region: "Latin America" },
  { city: "Puerto Vallarta", airport: "PVR", region: "Latin America" },
  { city: "Acapulco", airport: "ACA", region: "Latin America" },
  { city: "Toluca", airport: "TLC", region: "Latin America" },
  { city: "Natal", airport: "NAT", region: "Latin America" },
  { city: "Maceio", airport: "MCZ", region: "Latin America" },
  { city: "Joao Pessoa", airport: "JPA", region: "Latin America" },
  { city: "Aracaju", airport: "AJU", region: "Latin America" },
  { city: "Cuiaba", airport: "CGB", region: "Latin America" },
  { city: "Campo Grande", airport: "CGR", region: "Latin America" },
  { city: "Florianopolis", airport: "FLN", region: "Latin America" },
  { city: "Vitoria", airport: "VIX", region: "Latin America" },
  { city: "Sao Luis", airport: "SLZ", region: "Latin America" },
  { city: "Teresina", airport: "THE", region: "Latin America" },
  { city: "Porto Velho", airport: "PVH", region: "Latin America" },
  { city: "Boa Vista", airport: "BVB", region: "Latin America" },
  { city: "Macapa", airport: "MCP", region: "Latin America" },
  { city: "Palmas", airport: "PMW", region: "Latin America" },
  { city: "Arequipa", airport: "AQP", region: "Latin America" },
  { city: "Cusco", airport: "CUZ", region: "Latin America" },
  { city: "Trujillo", airport: "TRU", region: "Latin America" },
  { city: "Piura", airport: "PIU", region: "Latin America" },
  { city: "Chiclayo", airport: "CIX", region: "Latin America" },
  { city: "Iquitos", airport: "IQT", region: "Latin America" },
  { city: "Valparaiso", airport: "SCL", region: "Latin America" },
  { city: "Concepcion", airport: "CCP", region: "Latin America" },
  { city: "Antofagasta", airport: "ANF", region: "Latin America" },
  { city: "Puerto Montt", airport: "PMC", region: "Latin America" },
  { city: "Temuco", airport: "ZCO", region: "Latin America" },
  { city: "Maracaibo", airport: "MAR", region: "Latin America" },
  { city: "Caracas", airport: "CCS", region: "Latin America" },
  { city: "Valencia", airport: "VLN", region: "Latin America" },
  { city: "Barquisimeto", airport: "BRM", region: "Latin America" },
  { city: "Maturin", airport: "MUN", region: "Latin America" },
  { city: "Paramaribo", airport: "PBM", region: "Latin America" },
  { city: "Georgetown", airport: "GEO", region: "Latin America" },
  { city: "Curacao", airport: "CUR", region: "Latin America" },
  { city: "Aruba", airport: "AUA", region: "Latin America" },
  { city: "Cochabamba", airport: "CBB", region: "Latin America" },
  { city: "Sucre", airport: "SRE", region: "Latin America" },

  // United States (50)
  { city: "New York", airport: "JFK", region: "United States" },
  { city: "Los Angeles", airport: "LAX", region: "United States" },
  { city: "Chicago", airport: "ORD", region: "United States" },
  { city: "Houston", airport: "IAH", region: "United States" },
  { city: "Phoenix", airport: "PHX", region: "United States" },
  { city: "Philadelphia", airport: "PHL", region: "United States" },
  { city: "San Antonio", airport: "SAT", region: "United States" },
  { city: "San Diego", airport: "SAN", region: "United States" },
  { city: "Dallas", airport: "DFW", region: "United States" },
  { city: "Fort Worth", airport: "DFW", region: "United States" },
  { city: "Jacksonville", airport: "JAX", region: "United States" },
  { city: "Austin", airport: "AUS", region: "United States" },
  { city: "San Jose", airport: "SJC", region: "United States" },
  { city: "Charlotte", airport: "CLT", region: "United States" },
  { city: "Columbus", airport: "CMH", region: "United States" },
  { city: "Indianapolis", airport: "IND", region: "United States" },
  { city: "San Francisco", airport: "SFO", region: "United States" },
  { city: "Seattle", airport: "SEA", region: "United States" },
  { city: "Denver", airport: "DEN", region: "United States" },
  { city: "Washington", airport: "IAD", region: "United States" },
  { city: "Boston", airport: "BOS", region: "United States" },
  { city: "El Paso", airport: "ELP", region: "United States" },
  { city: "Nashville", airport: "BNA", region: "United States" },
  { city: "Detroit", airport: "DTW", region: "United States" },
  { city: "Oklahoma City", airport: "OKC", region: "United States" },
  { city: "Portland", airport: "PDX", region: "United States" },
  { city: "Las Vegas", airport: "LAS", region: "United States" },
  { city: "Memphis", airport: "MEM", region: "United States" },
  { city: "Louisville", airport: "SDF", region: "United States" },
  { city: "Baltimore", airport: "BWI", region: "United States" },
  { city: "Milwaukee", airport: "MKE", region: "United States" },
  { city: "Albuquerque", airport: "ABQ", region: "United States" },
  { city: "Tucson", airport: "TUS", region: "United States" },
  { city: "Fresno", airport: "FAT", region: "United States" },
  { city: "Sacramento", airport: "SMF", region: "United States" },
  { city: "Mesa", airport: "PHX", region: "United States" },
  { city: "Kansas City", airport: "MCI", region: "United States" },
  { city: "Atlanta", airport: "ATL", region: "United States" },
  { city: "Long Beach", airport: "LGB", region: "United States" },
  { city: "Colorado Springs", airport: "COS", region: "United States" },
  { city: "Raleigh", airport: "RDU", region: "United States" },
  { city: "Miami", airport: "MIA", region: "United States" },
  { city: "Virginia Beach", airport: "ORF", region: "United States" },
  { city: "Omaha", airport: "OMA", region: "United States" },
  { city: "Oakland", airport: "OAK", region: "United States" },
  { city: "Minneapolis", airport: "MSP", region: "United States" },
  { city: "Tulsa", airport: "TUL", region: "United States" },
  { city: "Arlington", airport: "DFW", region: "United States" },
  { city: "New Orleans", airport: "MSY", region: "United States" },
  { city: "Wichita", airport: "ICT", region: "United States" },

  // Europe (50)
  { city: "Istanbul", airport: "IST", region: "Europe" },
  { city: "Moscow", airport: "SVO", region: "Europe" },
  { city: "London", airport: "LHR", region: "Europe" },
  { city: "Saint Petersburg", airport: "LED", region: "Europe" },
  { city: "Berlin", airport: "BER", region: "Europe" },
  { city: "Madrid", airport: "MAD", region: "Europe" },
  { city: "Kyiv", airport: "KBP", region: "Europe" },
  { city: "Rome", airport: "FCO", region: "Europe" },
  { city: "Paris", airport: "CDG", region: "Europe" },
  { city: "Bucharest", airport: "OTP", region: "Europe" },
  { city: "Vienna", airport: "VIE", region: "Europe" },
  { city: "Minsk", airport: "MSQ", region: "Europe" },
  { city: "Hamburg", airport: "HAM", region: "Europe" },
  { city: "Warsaw", airport: "WAW", region: "Europe" },
  { city: "Budapest", airport: "BUD", region: "Europe" },
  { city: "Barcelona", airport: "BCN", region: "Europe" },
  { city: "Munich", airport: "MUC", region: "Europe" },
  { city: "Kharkiv", airport: "HRK", region: "Europe" },
  { city: "Milan", airport: "MXP", region: "Europe" },
  { city: "Prague", airport: "PRG", region: "Europe" },
  { city: "Sofia", airport: "SOF", region: "Europe" },
  { city: "Brussels", airport: "BRU", region: "Europe" },
  { city: "Birmingham", airport: "BHX", region: "Europe" },
  { city: "Cologne", airport: "CGN", region: "Europe" },
  { city: "Naples", airport: "NAP", region: "Europe" },
  { city: "Turin", airport: "TRN", region: "Europe" },
  { city: "Stockholm", airport: "ARN", region: "Europe" },
  { city: "Amsterdam", airport: "AMS", region: "Europe" },
  { city: "Marseille", airport: "MRS", region: "Europe" },
  { city: "Valencia", airport: "VLC", region: "Europe" },
  { city: "Leeds", airport: "LBA", region: "Europe" },
  { city: "Krakow", airport: "KRK", region: "Europe" },
  { city: "Frankfurt", airport: "FRA", region: "Europe" },
  { city: "Rotterdam", airport: "AMS", region: "Europe" },
  { city: "Seville", airport: "SVQ", region: "Europe" },
  { city: "Lisbon", airport: "LIS", region: "Europe" },
  { city: "Zagreb", airport: "ZAG", region: "Europe" },
  { city: "Athens", airport: "ATH", region: "Europe" },
  { city: "Copenhagen", airport: "CPH", region: "Europe" },
  { city: "Dublin", airport: "DUB", region: "Europe" },
  { city: "Oslo", airport: "OSL", region: "Europe" },
  { city: "Helsinki", airport: "HEL", region: "Europe" },
  { city: "Edinburgh", airport: "EDI", region: "Europe" },
  { city: "Geneva", airport: "GVA", region: "Europe" },
  { city: "Zurich", airport: "ZRH", region: "Europe" },
  { city: "Porto", airport: "OPO", region: "Europe" },
  { city: "Lyon", airport: "LYS", region: "Europe" },
  { city: "Nice", airport: "NCE", region: "Europe" },
  { city: "Manchester", airport: "MAN", region: "Europe" },
  { city: "Palma de Mallorca", airport: "PMI", region: "Europe" },

  // Asia (50)
  { city: "Tokyo", airport: "HND", region: "Asia" },
  { city: "Delhi", airport: "DEL", region: "Asia" },
  { city: "Shanghai", airport: "PVG", region: "Asia" },
  { city: "Dhaka", airport: "DAC", region: "Asia" },
  { city: "Beijing", airport: "PEK", region: "Asia" },
  { city: "Mumbai", airport: "BOM", region: "Asia" },
  { city: "Osaka", airport: "KIX", region: "Asia" },
  { city: "Karachi", airport: "KHI", region: "Asia" },
  { city: "Chongqing", airport: "CKG", region: "Asia" },
  { city: "Istanbul", airport: "IST", region: "Asia" },
  { city: "Kolkata", airport: "CCU", region: "Asia" },
  { city: "Manila", airport: "MNL", region: "Asia" },
  { city: "Foshan", airport: "CAN", region: "Asia" }
  { city: "Tianjin", airport: "TSN", region: "Asia" },
  { city: "Guangzhou", airport: "CAN", region: "Asia" },
  { city: "Lahore", airport: "LHE", region: "Asia" },
  { city: "Bangalore", airport: "BLR", region: "Asia" },
  { city: "Shenzhen", airport: "SZX", region: "Asia" },
  { city: "Bangkok", airport: "BKK", region: "Asia" },
  { city: "Chennai", airport: "MAA", region: "Asia" },
  { city: "Jakarta", airport: "CGK", region: "Asia" },
  { city: "Seoul", airport: "ICN", region: "Asia" },
  { city: "Chengdu", airport: "TFU", region: "Asia" },
  { city: "Tehran", airport: "IKA", region: "Asia" },
  { city: "Ho Chi Minh City", airport: "SGN", region: "Asia" },
  { city: "Wuhan", airport: "WUH", region: "Asia" },
  { city: "Hong Kong", airport: "HKG", region: "Asia" },
  { city: "Xi'an", airport: "XIY", region: "Asia" },
  { city: "Ahmedabad", airport: "AMD", region: "Asia" },
  { city: "Hyderabad", airport: "HYD", region: "Asia" },
  { city: "Kuala Lumpur", airport: "KUL", region: "Asia" },
  { city: "Singapore", airport: "SIN", region: "Asia" },
  { city: "Riyadh", airport: "RUH", region: "Asia" },
  { city: "Jeddah", airport: "JED", region: "Asia" },
  { city: "Taipei", airport: "TPE", region: "Asia" },
  { city: "Hangzhou", airport: "HGH", region: "Asia" },
  { city: "Suzhou", airport: "SHA", region: "Asia" },
  { city: "Nanjing", airport: "NKG", region: "Asia" },
  { city: "Fukuoka", airport: "FUK", region: "Asia" },
  { city: "Sapporo", airport: "CTS", region: "Asia" },
  { city: "Nagoya", airport: "NGO", region: "Asia" },
  { city: "Phnom Penh", airport: "PNH", region: "Asia" },
  { city: "Hanoi", airport: "HAN", region: "Asia" },
  { city: "Da Nang", airport: "DAD", region: "Asia" },
  { city: "Ulaanbaatar", airport: "UBN", region: "Asia" },
  { city: "Almaty", airport: "ALA", region: "Asia" },
  { city: "Tashkent", airport: "TAS", region: "Asia" },
  { city: "Doha", airport: "DOH", region: "Asia" },
  { city: "Dubai", airport: "DXB", region: "Asia" },
  { city: "Abu Dhabi", airport: "AUH", region: "Asia" }
];

export const rewardsPrograms = [
  { name: "American AAdvantage", type: "airline", alliance: "oneworld", transferPartners: ["Bilt", "Marriott"] },
  { name: "Alaska Mileage Plan", type: "airline", alliance: "oneworld", transferPartners: ["Bilt", "Marriott"] },
  { name: "United MileagePlus", type: "airline", alliance: "Star Alliance", transferPartners: ["Chase", "Bilt", "Marriott"] },
  { name: "Delta SkyMiles", type: "airline", alliance: "SkyTeam", transferPartners: ["Amex", "Marriott"] },
  { name: "Air Canada Aeroplan", type: "airline", alliance: "Star Alliance", transferPartners: ["Amex", "Chase", "Capital One", "Bilt", "Marriott"] },
  { name: "Air France-KLM Flying Blue", type: "airline", alliance: "SkyTeam", transferPartners: ["Amex", "Chase", "Citi", "Capital One", "Bilt", "Marriott"] },
  { name: "British Airways Executive Club", type: "airline", alliance: "oneworld", transferPartners: ["Amex", "Chase", "Capital One", "Bilt", "Marriott"] },
  { name: "Iberia Plus", type: "airline", alliance: "oneworld", transferPartners: ["Amex", "Chase", "Bilt", "Marriott"] },
  { name: "Qatar Airways Privilege Club", type: "airline", alliance: "oneworld", transferPartners: ["Amex", "Citi", "Capital One", "Bilt", "Marriott"] },
  { name: "Virgin Atlantic Flying Club", type: "airline", alliance: "SkyTeam", transferPartners: ["Amex", "Chase", "Citi", "Capital One", "Bilt", "Marriott"] },
  { name: "Singapore KrisFlyer", type: "airline", alliance: "Star Alliance", transferPartners: ["Amex", "Chase", "Citi", "Capital One", "Marriott"] },
  { name: "Emirates Skywards", type: "airline", alliance: "Independent", transferPartners: ["Amex", "Chase", "Citi", "Capital One", "Bilt", "Marriott"] },
  { name: "Etihad Guest", type: "airline", alliance: "Independent", transferPartners: ["Amex", "Citi", "Capital One", "Marriott"] },
  { name: "Turkish Miles&Smiles", type: "airline", alliance: "Star Alliance", transferPartners: ["Citi", "Capital One", "Bilt", "Marriott"] },
  { name: "Avianca LifeMiles", type: "airline", alliance: "Star Alliance", transferPartners: ["Amex", "Citi", "Capital One", "Bilt", "Marriott"] },
  { name: "Cathay Pacific Asia Miles", type: "airline", alliance: "oneworld", transferPartners: ["Amex", "Citi", "Capital One", "Bilt", "Marriott"] },
  { name: "ANA Mileage Club", type: "airline", alliance: "Star Alliance", transferPartners: ["Amex", "Marriott"] },
  { name: "Qantas Frequent Flyer", type: "airline", alliance: "oneworld", transferPartners: ["Amex", "Capital One", "Citi", "Marriott"] },
  { name: "TAP Miles&Go", type: "airline", alliance: "Star Alliance", transferPartners: ["Capital One", "Marriott"] },
  { name: "Southwest Rapid Rewards", type: "airline", alliance: "Independent", transferPartners: ["Chase", "Marriott"] },
  { name: "JetBlue TrueBlue", type: "airline", alliance: "Independent", transferPartners: ["Chase", "Citi", "Capital One", "Marriott"] },
  { name: "Hilton Honors", type: "hotel", alliance: "Hotel", transferPartners: ["Amex", "Bilt"] },
  { name: "Marriott Bonvoy", type: "hotel", alliance: "Hotel", transferPartners: ["Amex", "Chase", "Citi", "Capital One", "Bilt"] },
  { name: "World of Hyatt", type: "hotel", alliance: "Hotel", transferPartners: ["Chase", "Bilt"] },
  { name: "IHG One Rewards", type: "hotel", alliance: "Hotel", transferPartners: ["Chase", "Bilt"] }
];

export const airlineInfo = {
  "American AAdvantage": { name: "American Airlines", emoji: "🇺🇸", cashUrl: "https://www.aa.com/", pointsUrl: "https://www.aa.com/" },
  "Alaska Mileage Plan": { name: "Alaska Airlines", emoji: "🇺🇸", cashUrl: "https://www.alaskaair.com/", pointsUrl: "https://www.alaskaair.com/" },
  "United MileagePlus": { name: "United Airlines", emoji: "🇺🇸", cashUrl: "https://www.united.com/", pointsUrl: "https://www.united.com/" },
  "Delta SkyMiles": { name: "Delta Air Lines", emoji: "🇺🇸", cashUrl: "https://www.delta.com/", pointsUrl: "https://www.delta.com/" },
  "Air Canada Aeroplan": { name: "Air Canada", emoji: "🇨🇦", cashUrl: "https://www.aircanada.com/", pointsUrl: "https://www.aircanada.com/" },
  "Air France-KLM Flying Blue": { name: "Air France / KLM", emoji: "🇫🇷", cashUrl: "https://www.flyingblue.com/", pointsUrl: "https://www.flyingblue.com/" },
  "British Airways Executive Club": { name: "British Airways", emoji: "🇬🇧", cashUrl: "https://www.britishairways.com/", pointsUrl: "https://www.britishairways.com/" },
  "Iberia Plus": { name: "Iberia", emoji: "🇪🇸", cashUrl: "https://www.iberia.com/", pointsUrl: "https://www.iberia.com/" },
  "Qatar Airways Privilege Club": { name: "Qatar Airways", emoji: "🇶🇦", cashUrl: "https://www.qatarairways.com/", pointsUrl: "https://www.qatarairways.com/" },
  "Virgin Atlantic Flying Club": { name: "Virgin Atlantic", emoji: "🇬🇧", cashUrl: "https://www.virginatlantic.com/", pointsUrl: "https://www.virginatlantic.com/" },
  "Singapore KrisFlyer": { name: "Singapore Airlines", emoji: "🇸🇬", cashUrl: "https://www.singaporeair.com/", pointsUrl: "https://www.singaporeair.com/" },
  "Emirates Skywards": { name: "Emirates", emoji: "🇦🇪", cashUrl: "https://www.emirates.com/", pointsUrl: "https://www.emirates.com/" },
  "Etihad Guest": { name: "Etihad Airways", emoji: "🇦🇪", cashUrl: "https://www.etihad.com/", pointsUrl: "https://www.etihad.com/" },
  "Turkish Miles&Smiles": { name: "Turkish Airlines", emoji: "🇹🇷", cashUrl: "https://www.turkishairlines.com/", pointsUrl: "https://www.turkishairlines.com/" },
  "Avianca LifeMiles": { name: "Avianca", emoji: "🇨🇴", cashUrl: "https://www.avianca.com/", pointsUrl: "https://www.lifemiles.com/" },
  "Cathay Pacific Asia Miles": { name: "Cathay Pacific", emoji: "🇭🇰", cashUrl: "https://www.cathaypacific.com/", pointsUrl: "https://www.cathaypacific.com/" },
  "ANA Mileage Club": { name: "ANA", emoji: "🇯🇵", cashUrl: "https://www.ana.co.jp/", pointsUrl: "https://www.ana.co.jp/" },
  "Qantas Frequent Flyer": { name: "Qantas", emoji: "🇦🇺", cashUrl: "https://www.qantas.com/", pointsUrl: "https://www.qantas.com/" },
  "TAP Miles&Go": { name: "TAP Air Portugal", emoji: "🇵🇹", cashUrl: "https://www.flytap.com/", pointsUrl: "https://www.flytap.com/" },
  "Southwest Rapid Rewards": { name: "Southwest", emoji: "🇺🇸", cashUrl: "https://www.southwest.com/", pointsUrl: "https://www.southwest.com/" },
  "JetBlue TrueBlue": { name: "JetBlue", emoji: "🇺🇸", cashUrl: "https://www.jetblue.com/", pointsUrl: "https://www.jetblue.com/" },
  "Hilton Honors": { name: "Hilton", emoji: "🏨", cashUrl: "https://www.hilton.com/", pointsUrl: "https://www.hilton.com/" },
  "Marriott Bonvoy": { name: "Marriott", emoji: "🏨", cashUrl: "https://www.marriott.com/", pointsUrl: "https://www.marriott.com/" },
  "World of Hyatt": { name: "Hyatt", emoji: "🏨", cashUrl: "https://world.hyatt.com/", pointsUrl: "https://world.hyatt.com/" },
  "IHG One Rewards": { name: "IHG", emoji: "🏨", cashUrl: "https://www.ihg.com/", pointsUrl: "https://www.ihg.com/" }
} as const;
